config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/new_trigger_message'
  get 'home/new_excel_gen'
  get 'home/new_source_trigger'
  post 'home/file_process_trigger'
  post 'home/process_excel'
  post 'home/process_sources_trigger'

  get 'elasticsearch/login', to: 'elastic_search#login'
  post 'elasticsearch/authenticate', to: 'elastic_search#authenticate'
  delete 'elasticsearch/logout', to: 'elastic_search#logout'

  get 'elasticsearch/choose_index', to: 'elastic_search#choose_index'

  get 'elasticsearch/search_form', to: 'elastic_search#search_form'
  delete 'elasticsearch/clear_search_session', to: 'elastic_search#clear_search_session'
  get 'elasticsearch/search_results', to: 'elastic_search#search_results'
  get 'elasticsearch/view_cluster', to: 'elastic_search#view_cluster'

  get 'saga_json/login', to: 'saga_json#login'
  post 'saga_json/authenticate', to: 'saga_json#authenticate'
  delete 'saga_json/logout', to: 'saga_json#logout'

  get 'saga_json/search_form', to: 'saga_json#search_form'
  delete 'saga_json/clear_search_session', to: 'saga_json#clear_search_session'
  get 'saga_json/search_results', to: 'saga_json#search_results'

  post 'saga_json/refresh_saga_data', to: 'saga_json#refresh_saga_data'
  post 'saga_json/download_saga_report', to: 'saga_json#download_saga_report'

  get 'result_hash/get_input', to: 'result_hash#get_input'
  post 'result_hash/process_input', to: 'result_hash#process_input'
  get 'result_hash/index', to: 'result_hash#index'
  delete 'result_hash/clear_result_hash', to: 'result_hash#clear_result_hash'
  delete 'result_hash/clear_specific_result_hash', to: 'result_hash#clear_specific_result_hash'
end

app/controllers/home_controller.rb
require 'axlsx'

class HomeController < ApplicationController
  def index
  end

  def new_trigger_message
  end

  def new_excel_gen
  end

  def new_source_trigger
    @source_names = all_source_names
  end

  def file_process_trigger
    entity_name = params[:entity_type]
    entity_profile = get_profile(entity_name)
    batch_size = params[:batch_size].to_i
    flag = get_flag_json(params[:flag])
    file = params[:file]
    fetch_batch_id = params[:batch_id_gen].present?
    output_file_name = "trig_msg_#{Time.now.strftime('%H:%M:%S')}"
    file_content = generate_trigger_file(entity_name, entity_profile, batch_size, flag, file, fetch_batch_id)
    content_string = file_content.join("\n")
    send_data content_string, filename: "#{output_file_name}.txt", type: "text/plain"
  end

  def process_excel
    file = params[:file]
    output_file_name = "ingestion_report_#{Time.now.strftime('%H:%M:%S')}.xlsx"
    xlsx_package = generate_xlsx(file)
    send_data xlsx_package.to_stream.read, filename: output_file_name, type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  end

  def process_sources_trigger
    entity_name = params[:entity_type]
    entity_profile = get_profile(entity_name)
    batch_size = params[:batch_size].to_i
    flag = get_flag_json(params[:flag])
    selected_sources = params[:selected_order]
    if selected_sources.present?
      source_names = selected_sources.split(',')
      output_file_name = "trig_msg_#{Time.now.strftime('%H:%M:%S')}"
      file_content = trigger_msg_sources(entity_name, entity_profile, batch_size, flag, source_names)
      content_string = file_content.join("\n")
      send_data content_string, filename: "#{output_file_name}.txt", type: "text/plain"
    else
      flash[:alert] = "Select atleast one source from the list"
      render 'home/index'
    end
  end

  private

  def get_flag_json(flag_type)
    case flag_type
    when 'NO_FLAG'
      nil
    when 'OVERWRITE'
      { 'overwriteRecords': true }.as_json
    when 'FORCE'
      { 'forceReMatchOnDupes': true }.as_json
    when 'OVERWRITE_FORCE'
      { 'overwriteRecords': true, 'forceReMatchOnDupes': true }.as_json
    else
      nil
    end
  end

  def get_profile(entity_type)
    case entity_type
    when 'provider'
      'http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitionerrole'
    when 'facility'
      'http://hl7.org/fhir/us/core/STU5.0.1/StructureDefinition/us-core-OrganizationAffiliation'
    else
      nil
    end
  end

  def all_source_names
    %w[wa-kaiserwa wa-kaisernw wa-regence-bs wa-premera wa-amerigroup wa-molina wa-uhc wa-deltadental wa-dentegra wa-chpw wa-lifewise wa-bridgespan wa-cc-medicaid wa-cc-exchange wa-pacificsource or-regence-bcbs or-uhc wa-licensure us-nppes wa-cc-cascade]
  end

  def file_read_sort(file)
    lines = File.readlines(file).map(&:chomp)
    cleaned_lines = lines.compact.map(&:strip).reject(&:blank?)
    sort_arr = cleaned_lines.each_slice(4).to_a
    sort_arr.sort_by { |_, _, _, size| size.to_f }
  end

  def clean_up_fields(each_line_set, entity_name, fetch_batch_id)
    source_name = each_line_set[0].downcase
    source_name = all_source_names.include?(source_name) ? source_name : 'not_valid_source'
    path = each_line_set[1]
    path = (path.starts_with?('https') && path.ends_with?('ndjson')) ? path : 'url_issue'
    date = each_line_set[2]
    size = each_line_set[3]
    file_name = File.basename(path)
    batch_id = if fetch_batch_id.present? && file_name.present? && (file_name.include?('provider:') || file_name.include?('facility:'))
                 file_name.match(/(provider|facility):(.{1,36})/)[0] rescue "#{entity_name}:#{SecureRandom.uuid}"
               else
                 "#{entity_name}:#{SecureRandom.uuid}"
               end
    [source_name, size, file_name, path, date, batch_id]
  end

  def generate_trigger_file(entity_name, entity_profile, batch_size, flag, file, fetch_batch_id)
    sorted_lines = file_read_sort(file)
    write_arr = []
    sl_no = 1
    sorted_lines.each do |each_line_set|
      source_name, size, file_name, path, date, batch_id = clean_up_fields(each_line_set, entity_name, fetch_batch_id)
      write_arr << "#{sl_no}. #{source_name} [#{size}, #{date}]\n\n\n"
      trigger_msg_json = {
        "meta": {
          "SourceCode": source_name,
          "SourceFilePath": path,
          "profile": entity_profile,
          "batchId": batch_id
        },
        "processRules": {
          "batchSize": batch_size
        }
      }.as_json
      flag.present? ? trigger_msg_json['processRules'].merge!(flag) : nil
      write_arr << JSON.pretty_generate(trigger_msg_json, indent: '    ')
      write_arr << "\n\n"
      write_arr << '--------------------------------------------------------'
      sl_no += 1
    end
    write_arr
  end

  def generate_xlsx(file)
    xlsx = Axlsx::Package.new
    workbook = xlsx.workbook
    header_style = workbook.styles.add_style(bg_color: 'cccccc', b: true, border: Axlsx::STYLE_THIN_BORDER)
    worksheet = workbook.add_worksheet
    row_style = worksheet.styles.add_style(border: Axlsx::STYLE_THIN_BORDER)
    headers = ['SL.NO', 'Source Name', 'Size', 'File Name', 'Path', 'Date', 'Ingested Date', 'Ingestion Status', 'ndjson Verified']
    worksheet.add_row(headers, style: header_style)
    sorted_lines = file_read_sort(file)
    row_num = 1
    sl_no = 1
    sorted_lines.each do |each_line_set|
      source_name, size, file_name, path, date, batch_id = clean_up_fields(each_line_set, '', false)
      row_data = [sl_no, source_name, size, file_name, path, date, Date.today.strftime("%m/%d/%Y"), 'In Progress', 'In Progress']
      worksheet.add_row(row_data, style: row_style)
      row_num += 1
      sl_no += 1
    end
    xlsx
  end

  def trigger_msg_sources(entity_name, entity_profile, batch_size, flag, source_names)
    write_arr = []
    sl_no = 1
    source_names.each do |source_name|
      write_arr << "#{sl_no}. #{source_name}\n\n\n"
      trigger_msg_json = {
        "meta": {
          "SourceCode": source_name,
          "SourceFilePath": 'replace_file_url',
          "profile": entity_profile,
          "batchId": "#{entity_name}:#{SecureRandom.uuid}"
        },
        "processRules": {
          "batchSize": batch_size
        }
      }.as_json
      flag.present? ? trigger_msg_json['processRules'].merge!(flag) : nil
      write_arr << JSON.pretty_generate(trigger_msg_json, indent: '    ')
      write_arr << "\n\n"
      write_arr << '--------------------------------------------------------'
      sl_no += 1
    end
    write_arr
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2">Welcome to Clarity Helper</h2>
              <p class="text-white-50 mb-5">Work made easy!</p>

              <% if session[:elastic_ip].present? %>
                <div class="form-outline form-white mb-4">
                  <%= link_to 'Elastic Search', elasticsearch_choose_index_path, class: "btn btn-primary" %>
                </div>
              <% else %>
                <div class="form-outline form-white mb-4">
                  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    Elastic Search
                  </button>
                </div>
              <% end %>

              <% if session[:saga_json_url].present? %>
                <div class="form-outline form-white mb-4">
                  <%= link_to 'Saga Json Viewer', saga_json_search_form_path, class: "btn btn-primary" %>
                </div>
              <% else %>
                <div class="form-outline form-white mb-4">
                  <%= link_to 'Saga Json Viewer', saga_json_login_path, class: "btn btn-primary" %>
                </div>
              <% end %>

              <div class="form-outline form-white mb-4">
                <%= link_to 'Validate Result Hash', result_hash_get_input_path, class: "btn btn-primary" %>
              </div>

<!--              <div class="form-outline form-white mb-4">-->
                <%#= link_to 'Generate Trigger Message Based On File', home_new_trigger_message_path, class: "btn btn-primary" %>
<!--              </div>-->


<!--              <div class="form-outline form-white mb-4">-->
                <%#= link_to 'Generate Ingestion Report Based On File', home_new_excel_gen_path, class: "btn btn-primary" %>
<!--              </div>-->

              <div class="form-outline form-white mb-4">
                <%= link_to 'Generate Trigger Message Based On Source', home_new_source_trigger_path, class: "btn btn-primary" %>
              </div>

            </div>

            <!-- Modal -->
            <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title text-dark" id="staticBackdropLabel">Choose ES type</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">

                    <div class="form-outline form-white mb-4">
                      <%= link_to 'With Authentication', elasticsearch_login_path(auth: true), class: "btn btn-primary" %>
                    </div>

                    <div class="form-outline form-white mb-4">
                      <%= link_to 'Without Authentication', elasticsearch_login_path(auth: false), class: "btn btn-primary" %>
                    </div>

                  </div>
                  <!--                  <div class="modal-footer">-->
                  <!--                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>-->
                  <!--                  </div>-->
                </div>
              </div>
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/new_excel_gen.html.erb
<section class="gradient-custom-blue">
  <br>
  <div class="container py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-5">

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Generate Ingestion Report</h3>

            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <%= form_tag({ controller: "home", action: "process_excel" }, method: "post", multipart: true) do %>

                <%= file_field_tag :file, class: "form-control", required: true %>
                <br>
                <p class="text-secondary" , style="font-size: 15px">Content order: source_name url date size</p>
                <br>

                <%= submit_tag "Proceed", class: "btn btn-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/new_source_trigger.html.erb
<section class="gradient-custom-blue">
  <br>
  <div class="container py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-7">

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Generate Trigger Message</h3>

            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <%= form_tag({ controller: "home", action: "process_sources_trigger" }, method: "post", multipart: true) do %>

                <%= select_tag(:entity_type, options_for_select([["Select Entity Type", ""], ["Provider", "provider"], ["Facility", "facility"]], params[:entity_type]), class: "select form-select", required: true) %>
                <br>

                <div class="form-outline form-white mb-4">
                  <%= number_field_tag :batch_size, nil, required: true, placeholder: 'Enter batch size', class: 'form-control' %>
                </div>

                <%= select_tag(:flag, options_for_select([["Select Flag", ""], ["No Flag", "NO_FLAG"], ["overwriteRecords", "OVERWRITE"], ["forceReMatchOnDupes", "FORCE"], ["overwriteRecords and forceReMatchOnDupes", "OVERWRITE_FORCE"]], params[:flag]), class: "select form-select", required: true) %>
                <br>

                <%= hidden_field_tag "selected_order", "", id: "selected_order" %>
                <div class="container">
                  <div class="row">
                    <% @source_names.each do |source_name| %>
                      <div class="col-md-6">
                        <div class="form-check">
                          <%= check_box_tag "items[]", source_name, false, class: "form-check-input", id: source_name %>
                          <%= label_tag source_name, source_name, class: "form-check-label" %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>

                <br>
                <div class="container text-center mb-4">
                  <p id="count-list" class="badge bg-light text-dark">Total Selected:
                    <span id="selected-items-count"></span></p>
                  <ul id="selected-items-list" class="list-group list-group-numbered"></ul>
                </div>


                <%= submit_tag "Proceed", class: "btn btn-success" %>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const checkboxes = document.querySelectorAll('input[type="checkbox"]');
        const selectedOrderInput = document.getElementById("selected_order");
        const selectedOrder = [];
        const selectedItemsList = document.getElementById("selected-items-list");
        const selectedItemsCount = document.getElementById("selected-items-count");
        const countList = document.getElementById("count-list");
        selectedItemsCount.innerHTML = 0;

        checkboxes.forEach(checkbox => {
            checkbox.addEventListener("change", function () {
                if (this.checked) {
                    selectedOrder.push(this.value);
                    updateSelectedItemsList();
                } else {
                    const index = selectedOrder.indexOf(this.value);
                    if (index > -1) {
                        selectedOrder.splice(index, 1);
                        updateSelectedItemsList();
                    }
                }
                selectedOrderInput.value = selectedOrder.join(",");
            });
        });

        function updateSelectedItemsList() {
            selectedItemsList.innerHTML = "";
            selectedItemsCount.innerHTML = selectedOrder.length;
            selectedOrder.forEach(item => {
                const li = document.createElement("li");
                li.textContent = item;
                li.classList.add("list-group-item");
                selectedItemsList.appendChild(li);
            });
        }
    });
</script>

app/views/home/new_trigger_message.html.erb
<section class="gradient-custom-blue">
  <br>
  <div class="container py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-5">

        <div class="card mb-5" style="border-radius: 15px;">
          <div class="card-body p-4 text-md-center">
            <h3 class="mb-3">Generate Trigger Message</h3>

            <hr class="my-4">
            <div class="justify-content-start align-items-center text-md-center">

              <%= form_tag({ controller: "home", action: "file_process_trigger" }, method: "post", multipart: true) do %>

                <%= select_tag(:entity_type, options_for_select([["Select Entity Type", ""], ["Provider", "provider"], ["Facility", "facility"]], params[:entity_type]), class: "select form-select", required: true) %>
                <br>

                <div class="form-outline form-white mb-4">
                  <%= number_field_tag :batch_size, nil, required: true, placeholder: 'Enter batch size', class: 'form-control' %>
                </div>

                <%= select_tag(:flag, options_for_select([["Select Flag", ""], ["No Flag", "NO_FLAG"], ["overwriteRecords", "OVERWRITE"], ["forceReMatchOnDupes", "FORCE"], ["overwriteRecords and forceReMatchOnDupes", "OVERWRITE_FORCE"]], params[:flag]), class: "select form-select", required: true) %>
                <br>

                <div class="form form-switch mb-4">
                  <%= check_box_tag :batch_id_gen, nil, true, class: 'form-check-input' %>
                  <label class="form-check-label" data-bs-toggle="tooltip" title="It can generate unique batchId if turned off">Fetch
                    batchId from url</label>
                </div>

                <%= file_field_tag :file, class: "form-control", required: true %>
                <br>
                <p class="text-secondary" , style="font-size: 15px">Content order: source_name url date size</p>
                <br>

                <%= submit_tag "Proceed", class: "btn btn-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>