config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/new_trigger_message'
  get 'home/new_excel_gen'
  get 'home/new_source_trigger'
  post 'home/file_process_trigger'
  post 'home/process_excel'
  post 'home/process_sources_trigger'

  get 'elasticsearch/login', to: 'elastic_search#login'
  post 'elasticsearch/authenticate', to: 'elastic_search#authenticate'
  delete 'elasticsearch/logout', to: 'elastic_search#logout'

  get 'elasticsearch/choose_index', to: 'elastic_search#choose_index'

  get 'elasticsearch/search_form', to: 'elastic_search#search_form'
  delete 'elasticsearch/clear_search_session', to: 'elastic_search#clear_search_session'
  get 'elasticsearch/search_results', to: 'elastic_search#search_results'
  get 'elasticsearch/view_cluster', to: 'elastic_search#view_cluster'

  get 'saga_json/login', to: 'saga_json#login'
  post 'saga_json/authenticate', to: 'saga_json#authenticate'
  delete 'saga_json/logout', to: 'saga_json#logout'

  get 'saga_json/search_form', to: 'saga_json#search_form'
  delete 'saga_json/clear_search_session', to: 'saga_json#clear_search_session'
  get 'saga_json/search_results', to: 'saga_json#search_results'

  post 'saga_json/refresh_saga_data', to: 'saga_json#refresh_saga_data'
  post 'saga_json/download_saga_report', to: 'saga_json#download_saga_report'

  get 'result_hash/get_input', to: 'result_hash#get_input'
  post 'result_hash/process_input', to: 'result_hash#process_input'
  get 'result_hash/index', to: 'result_hash#index'
  delete 'result_hash/clear_result_hash', to: 'result_hash#clear_result_hash'
  delete 'result_hash/clear_specific_result_hash', to: 'result_hash#clear_specific_result_hash'
end

app/controllers/result_hash_controller.rb
class ResultHashController < ApplicationController

  def get_input
    unless session[:uniq_result_hash_id].present?
      clear_all_tmp_result_hash
    end
  end

  def process_input
    begin
      result_hash = JSON.parse(params[:inputResultHash])

      result_hash_checked = {}
      file_path = session[:uniq_result_hash_path]
      file_path = create_empty_file unless file_path.present? && File.exist?(file_path)
      parsed_result_hashes = JSON.parse(File.read(file_path))
      if result_hash.is_a?(Hash)
        result_hash['entity_type'] = get_entity_type(result_hash['index_name'])
        if result_hash['entity_type'] == 'tenant_index'
          result_hash_checked = tenant_index(result_hash)
        else
          result_hash_checked = single_doc_index(result_hash)
        end
        parsed_result_hashes << result_hash_checked
      elsif result_hash.is_a?(Array)
        result_hash.each do |e_hash|
          unless e_hash['tenant'].present? && e_hash['ENV'].present? && e_hash['index_name'].present?
            flash[:alert] = "Missing tenant/ENV/Index_name"
            redirect_to result_hash_get_input_path
          end
          e_hash['entity_type'] = get_entity_type(e_hash['index_name'])
          if e_hash['entity_type'] == 'tenant_index'
            result_hash_checked = tenant_index(e_hash)
          else
            result_hash_checked = single_doc_index(e_hash)
          end
          parsed_result_hashes << result_hash_checked
        end
      else
        flash[:alert] = "Please provide a JSON object"
        redirect_to result_hash_get_input_path
      end
      File.open(file_path, 'w') { |file| file.write(parsed_result_hashes.to_json) }
      redirect_to result_hash_index_path
    rescue
      flash[:alert] = "Error in Parsing JSON. Check the result_hash"
      redirect_to result_hash_get_input_path
    end
  end

  def index
    file_path = session[:uniq_result_hash_path]
    @result_hashes = JSON.parse(File.read(file_path)) if file_path.present? && File.exist?(file_path)
    unless @result_hashes.present?
      flash[:alert] = "No existing result hashes to Show"
      redirect_to result_hash_get_input_path
    end
  end

  def clear_result_hash
    clear_all_tmp_result_hash
    flash[:notice] = "Existing result hashes cleared"
    redirect_to result_hash_get_input_path
  end

  def clear_specific_result_hash
    result_hash_id = params['result_hash_id']
    file_path = session[:uniq_result_hash_path]
    result_hashes = JSON.parse(File.read(file_path))
    result_hashes.delete_if { |each_hash| each_hash['result_hash_id'] == result_hash_id }
    File.open(file_path, 'w') { |file| file.write(result_hashes.to_json) }
    if result_hashes.present?
      redirect_to result_hash_index_path
    else
      redirect_to result_hash_get_input_path
    end
  end

  private

  def create_empty_file
    uniq_id = SecureRandom.uuid
    session[:uniq_result_hash_id] = uniq_id
    file_path = Rails.root.join('tmp', "#{session[:uniq_result_hash_id]}_result_hashess.json")
    session[:uniq_result_hash_path] = file_path
    File.open(file_path, 'w') { |file| file.write([]) }
    file_path
  end

  def clear_all_tmp_result_hash
    public_directory = Rails.root.join('tmp')
    Dir.glob(File.join(public_directory, '*')).each do |file_path|
      if File.basename(file_path) == "#{session[:uniq_result_hash_id]}_result_hashess.json"
        FileUtils.rm_rf(file_path)
      end
    end
    uniq_id = SecureRandom.uuid
    session[:uniq_result_hash_id] = uniq_id
    file_path = Rails.root.join('tmp', "#{session[:uniq_result_hash_id]}_result_hashess.json")
    session[:uniq_result_hash_path] = file_path
    File.open(file_path, 'w') { |file| file.write([]) }
  end

  def get_entity_type(index_name)
    if index_name.downcase.include?('facility') || index_name.downcase.include?('provider')
      'tenant_index'
    else
      'single_doc_index'
    end
  end

  def tenant_index(result_hash)
    red_count = 0
    result_hash.each do |key, value|
      next if %w[entity tenant ENV index_name].include?(key)

      if key == 'location' && value['location_must_not_exist'] != 0
        value['outputColor'] = 'red'
      end

      if value['total_records_in_db'].present?
        if value.count > 7
          value['extra_batch_id_count'] = value.count - 7
        end

        if value['difference'] != 0 || value['difference'].to_s == 'false'
          value['outputColor'] = 'red'
          red_count += 1
          value['note'] = value['difference'] < 0 ? 'Old records are still present in index' : 'Few records have to be send for Index'
        else
          value['outputColor'] = 'green'
        end
      end
    end
    result_hash['result_hash_id'] = SecureRandom.uuid
    result_hash['accordion_head_colour'] = red_count == 0 ? 'black' : 'red'
    result_hash['red_count'] = red_count
    excluded_keys = %w[entity tenant ENV index_name location entity_type accordion_head_colour red_count result_hash_id]
    result_hash['total_source_count'] = result_hash.keys.reject { |key| excluded_keys.include?(key) }.count
    result_hash
  end

  def single_doc_index(result_hash)
    red_count = 0
    result_hash.each do |key, value|
      next if %w[entity tenant ENV index_name].include?(key)

      if key == 'location' && value['location_must_not_exist'] != 0
        value['outputColor'] = 'red'
      end

      if value['total_records_in_db'].present?
        if value.count > 6
          value['extra_batch_id_count'] = value.count - 6
        end

        if value['difference'] != 0 || value['difference'].to_s == 'false'
          value['outputColor'] = 'red'
          red_count += 1
          value['note'] = value['difference'] < 0 ? 'Old records are still present in index' : 'Few records have to be send for Index'
        else
          value['outputColor'] = 'green'
        end
      end
    end
    result_hash['result_hash_id'] = SecureRandom.uuid
    result_hash['accordion_head_colour'] = red_count == 0 ? 'black' : 'red'
    result_hash['red_count'] = red_count
    excluded_keys = %w[entity tenant ENV index_name location entity_type accordion_head_colour red_count result_hash_id]
    result_hash['total_source_count'] = result_hash.keys.reject { |key| excluded_keys.include?(key) }.count
    result_hash
  end

end

app/views/result_hash/get_input.html.erb
<section class="vh-100 bg-light">

  <h2 class="fw-bold mb-3 text-center pt-3">INPUT RESULT HASH</h2>
  <div class="container text-center text-dark-50 mb-2 d-flex justify-content-center gap-2">
    <%= button_to 'Clear All Analysis', result_hash_clear_result_hash_path, method: :delete ,class: "btn btn-danger p-1 tooltip-arrow bs-tooltip-top", type: "button", "data-bs-toggle": "tooltip", "data-bs-placement": "top", title: "Clear all existing result hashes" %>
    <%= button_to 'View Analysis', result_hash_index_path, method: :get, class: "btn btn-success p-1 tooltip-arrow bs-tooltip-top", type: "button", "data-bs-toggle": "tooltip", "data-bs-placement": "top", title: "Go to result hash analysis page" %>
  </div>

  <div class="container p-2">
    <%= form_tag({ controller: "result_hash", action: "process_input" }, method: "post", multipart: true, class: "row g-3", id: "myForm") do %>

      <div class="col-md-12">
        <div class="form-outline form-white mb-4">
          <%= text_area_tag :inputResultHash, nil, placeholder: 'Result Hash', class: 'form-control', style: 'height: 400px;', required: true %>
        </div>
      </div>

      <div class="container text-center">
        <button type="reset" class="btn btn-danger text-center col-md-2" id="reset-btn">Reset</button>
        <%= submit_tag "Analyse", class: "btn btn-primary text-center col-md-2" %>
      </div>

    <% end %>
  </div>

</section>

app/views/result_hash/index.html.erb
<section class="vh-100 bg-light">

  <div class="container">

    <h3 class="fw-bold mt-3 text-center">RESULT HASH ANALYSIS</h3>
    <div class="d-flex justify-content-center mb-3">
      <%= button_to 'Add New', result_hash_get_input_path, method: :get, class: "btn btn-success p-1 tooltip-arrow bs-tooltip-top", type: "button", "data-bs-toggle": "tooltip", "data-bs-placement": "top", title: "Go to result hash input page" %>
    </div>

    <div class="text-end mb-3">
      <button id="collapseAll" class="btn" title="Collapse All">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrows-angle-contract" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M.172 15.828a.5.5 0 0 0 .707 0l4.096-4.096V14.5a.5.5 0 1 0 1 0v-3.975a.5.5 0 0 0-.5-.5H1.5a.5.5 0 0 0 0 1h2.768L.172 15.121a.5.5 0 0 0 0 .707M15.828.172a.5.5 0 0 0-.707 0l-4.096 4.096V1.5a.5.5 0 1 0-1 0v3.975a.5.5 0 0 0 .5.5H14.5a.5.5 0 0 0 0-1h-2.768L15.828.879a.5.5 0 0 0 0-.707"/>
        </svg>
      </button>
      <button id="expandAll" class="btn" title="Expand All">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrows-angle-expand" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M5.828 10.172a.5.5 0 0 0-.707 0l-4.096 4.096V11.5a.5.5 0 0 0-1 0v3.975a.5.5 0 0 0 .5.5H4.5a.5.5 0 0 0 0-1H1.732l4.096-4.096a.5.5 0 0 0 0-.707m4.344-4.344a.5.5 0 0 0 .707 0l4.096-4.096V4.5a.5.5 0 1 0 1 0V.525a.5.5 0 0 0-.5-.5H11.5a.5.5 0 0 0 0 1h2.768l-4.096 4.096a.5.5 0 0 0 0 .707"/>
        </svg>
      </button>
    </div>

    <% accordian_ids_count = 0 %>

    <% @result_hashes.each do |result_hash| %>
      <% accordian_ids_count += 1 %>
      <div class="accordion mb-1" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="<%= "panelsStayOpen-heading#{accordian_ids_count}" %>" >
            <button class="accordion-button collapsed fw-bold d-flex justify-content-between" type="button" data-bs-toggle="collapse" data-bs-target="<%= "#panelsStayOpen-collapse#{accordian_ids_count}" %>" aria-expanded="false" aria-controls="<%= "panelsStayOpen-collapse#{accordian_ids_count}" %>">
              <div class="flex-grow-1">
                <%= accordian_ids_count %>. <%= result_hash['ENV'].upcase %> | <%= result_hash['tenant'].downcase %>
                | <%= result_hash['index_name'] %>
              </div>
              <div class="pe-2" style="color: <%= result_hash&.dig('accordion_head_colour') %>;">
                <%= result_hash&.dig('red_count') != 0 ? "Error: #{result_hash&.dig('red_count')} |" : '' %> Total: <%= result_hash['total_source_count'] %>
              </div>
            </button>
          </h2>
          <div id="<%="panelsStayOpen-collapse#{accordian_ids_count}"%>" class="accordion-collapse collapse" aria-labelledby=<%= "panelsStayOpen-collapse#{accordian_ids_count}" %>>
            <div class="accordion-body">
              <% if result_hash['entity_type'] == 'tenant_index' %>
                <%= render 'result_hash/index_partials/tenant_index', locals: { result_hash: result_hash, count: accordian_ids_count } %>
              <% elsif result_hash['entity_type'] == 'single_doc_index' %>
                <%= render 'result_hash/index_partials/single_doc_index', locals: { result_hash: result_hash } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </div>

  <!-- Result Json Modal -->
  <div class="modal fade modal-lg" id="viewresulthash" data-bs-keyboard="false" tabindex="-1" aria-labelledby="viewresulthashLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title text-dark" id="viewresulthashLabel">Result Json</h5>

          <div class="ms-3">
            <button class="btn p-1 text-center" onclick="copyContent()" id="copy-button">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard" viewBox="0 0 16 16">
                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"/>
                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"/>
              </svg>
              Copy Json
            </button>
          </div>

          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <pre id="json-output-result-hash"></pre>
        </div>
      </div>
    </div>
  </div>

</section>


<script>
    function getResultHashVal(sourceKey) {
        try {
            return JSON.parse($('#view-result-hash-' + sourceKey).val());
        } catch (ex) {
            alert('Wrong JSON Format: ' + ex);
        }
    }

    function getSourceKey(button) {
        var sourceKey = button.value;
        document.getElementById("json-output-result-hash").textContent = JSON.stringify(getResultHashVal(sourceKey), undefined, 2);
    }

    const copyContent = async () => {
        try {
            let text = document.getElementById('json-output-result-hash').innerHTML;
            await navigator.clipboard.writeText(text);
            var originalCopyBtn = document.getElementById('copy-button').innerHTML
            document.getElementById('copy-button').innerHTML = 'Copied';
            setTimeout(() => {
                document.getElementById('copy-button').innerHTML = originalCopyBtn;
            }, 1000);
        } catch (err) {
            console.error('Failed to copy: ', err);
        }
    }

</script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const collapseAllButton = document.getElementById('collapseAll');
        const expandAllButton = document.getElementById('expandAll');

        collapseAllButton.addEventListener('click', function () {
            const accordions = document.querySelectorAll('.accordion-collapse');
            accordions.forEach(accordion => {
                if (accordion.classList.contains('show')) {
                    const button = accordion.previousElementSibling.querySelector('.accordion-button');
                    button.classList.add('collapsed');
                    button.setAttribute('aria-expanded', 'false');
                    accordion.classList.remove('show');
                }
            });
        });

        expandAllButton.addEventListener('click', function () {
            const accordions = document.querySelectorAll('.accordion-collapse');
            accordions.forEach(accordion => {
                if (!accordion.classList.contains('show')) {
                    const button = accordion.previousElementSibling.querySelector('.accordion-button');
                    button.classList.remove('collapsed');
                    button.setAttribute('aria-expanded', 'true');
                    accordion.classList.add('show');
                }
            });
        });
    });
</script>