config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/new_trigger_message'
  get 'home/new_excel_gen'
  get 'home/new_source_trigger'
  post 'home/file_process_trigger'
  post 'home/process_excel'
  post 'home/process_sources_trigger'

  get 'elasticsearch/login', to: 'elastic_search#login'
  post 'elasticsearch/authenticate', to: 'elastic_search#authenticate'
  delete 'elasticsearch/logout', to: 'elastic_search#logout'

  get 'elasticsearch/choose_index', to: 'elastic_search#choose_index'

  get 'elasticsearch/search_form', to: 'elastic_search#search_form'
  delete 'elasticsearch/clear_search_session', to: 'elastic_search#clear_search_session'
  get 'elasticsearch/search_results', to: 'elastic_search#search_results'
  get 'elasticsearch/view_cluster', to: 'elastic_search#view_cluster'

  get 'saga_json/login', to: 'saga_json#login'
  post 'saga_json/authenticate', to: 'saga_json#authenticate'
  delete 'saga_json/logout', to: 'saga_json#logout'

  get 'saga_json/search_form', to: 'saga_json#search_form'
  delete 'saga_json/clear_search_session', to: 'saga_json#clear_search_session'
  get 'saga_json/search_results', to: 'saga_json#search_results'

  post 'saga_json/refresh_saga_data', to: 'saga_json#refresh_saga_data'
  post 'saga_json/download_saga_report', to: 'saga_json#download_saga_report'

  get 'result_hash/get_input', to: 'result_hash#get_input'
  post 'result_hash/process_input', to: 'result_hash#process_input'
  get 'result_hash/index', to: 'result_hash#index'
  delete 'result_hash/clear_result_hash', to: 'result_hash#clear_result_hash'
  delete 'result_hash/clear_specific_result_hash', to: 'result_hash#clear_specific_result_hash'
end

app/controllers/elastic_search_controller.rb
class ElasticSearchController < ApplicationController

  def login
    redirect_to elasticsearch_choose_index_path if logged_in?
    @auth = params[:auth].present? && params[:auth].to_s == 'true'
  end

  def logout
    delete_session
    reset_chewy_client
    flash[:notice] = "Logout Successful"
    redirect_to root_path
  end

  def authenticate
    set_chewy_client(params)
    begin
      Chewy.client.cluster.health
      create_session(params)
      flash[:notice] = "Connection Successful"
      redirect_to elasticsearch_choose_index_path
    rescue
      flash[:alert] = "Connection Failed try again"
      redirect_to elasticsearch_login_path(params[:auth])
    end
  end

  def choose_index
    redirect_to elasticsearch_login_path unless logged_in?
    @provider_indexes = get_provider_indexes
    @facility_indexes = get_facility_indexes
  end

  def search_form
    session[:index_name] = params[:index_name] if params[:index_name]
    session[:entity_type] = get_entity_type(session[:index_name])
    set_chewy_client_for_execution(session[:elastic_ip], session[:elastic_username], session[:elastic_password])
    BaseModel.index_name(session[:index_name])
    @doc_count = BaseModel.exists? ? BaseModel.count : nil
  end

  def clear_search_session
    input_sessions = %w[inputName inputNpi inputSource inputUpdatedDate inputStableId inputLocStableId inputAddrText inputAddrCity inputAddrState inputAddrZip inputSize]
    input_sessions.map { |input| session[input] = nil }
    render status: :ok, body: nil
  end

  def search_results
    input_sessions = %i[inputName inputNpi inputSource inputUpdatedDate inputStableId inputLocStableId inputAddrText inputAddrCity inputAddrState inputAddrZip inputSize]
    input_sessions.map { |input| session[input] = params[input] }
    session[:inputSize] = params[:inputSize].present? ? params[:inputSize].to_i : 10000
    @search_query = form_elastic_query(params, session[:entity_type])
    set_chewy_client_for_execution(session[:elastic_ip], session[:elastic_username], session[:elastic_password])
    BaseModel.index_name(session[:index_name])
    @response = Chewy.client.search(index: session[:index_name], body: @search_query)
    @matched_doc_count = @response['hits']['total']['value']
    @matched_doc = @response['hits']['hits']
  end

  def view_cluster
    set_chewy_client_for_execution(session[:elastic_ip], session[:elastic_username], session[:elastic_password])
    BaseModel.index_name(session[:index_name])
    begin
      @index_document = BaseModel.find(params[:doc_id])._data
    rescue
      flash[:alert] = "Document not found"
      redirect_to elasticsearch_choose_index_path
    end
  end

  private

  def set_chewy_client_for_execution(elastic_ip, username, password)
    if elastic_ip && username && password
      Chewy.settings = { host: elastic_ip, user: username, password: password, request_timeout: 7 }
      Chewy.current[:chewy_client] = Chewy::ElasticClient.new
    else
      Chewy.settings = { host: elastic_ip, request_timeout: 7 }
      Chewy.current[:chewy_client] = Chewy::ElasticClient.new
    end
  end

  def set_chewy_client(params)
    ip_address = params[:ip_address]
    port = params[:port]
    username = params[:username]
    password = params[:password]
    elastic_ip = "#{params[:ip_address]}:#{params[:port]}"

    if ip_address && port && username && password
      Chewy.settings = { host: elastic_ip, user: username, password: password, request_timeout: 7 }
      Chewy.current[:chewy_client] = Chewy::ElasticClient.new
    else
      Chewy.settings = { host: elastic_ip, request_timeout: 7 }
      Chewy.current[:chewy_client] = Chewy::ElasticClient.new
    end
  end

  def reset_chewy_client
    Chewy.settings = { host: session[:elastic_ip] }
    Chewy.current[:chewy_client] = Chewy::ElasticClient.new
  end

  def create_session(params)
    session[:elastic_username] = params[:username]
    session[:elastic_password] = params[:password]
    session[:elastic_ip] = "#{params[:ip_address]}:#{params[:port]}"
    session[:logged_in] = true

    file_path = Rails.root.join('tmp', "#{session[:uniq_id]}_response.json")
    File.delete(file_path) if File.exist?(file_path)
    session[:uniq_id] = nil
    session[:saga_json_url] = nil
    session[:saga_json_key] = nil
  end

  def delete_session
    session[:elastic_username] = nil
    session[:elastic_password] = nil
    session[:elastic_ip] = nil
    session[:logged_in] = false
  end

  def logged_in?
    session[:elastic_ip].present? && session[:logged_in].present? && session[:logged_in].to_s == 'true'
  end

  def get_tenants
    %w[leaporbit wahbe centerlight riverspring honestmedical mddoh]
  end

  def get_provider_indexes
    pr_indexes = %w[provider_tenant_rw practitioner_role_tenant_rw]
    result_provider_indexes = []
    pr_indexes.each do |index|
      get_tenants.each do |tenant|
        result_provider_indexes << index.gsub('tenant', tenant)
      end
    end
    result_provider_indexes
  end

  def get_facility_indexes
    fac_indexes = %w[facility_tenant_rw organization_affiliation_tenant_rw practice_tenant_rw]
    result_facility_indexes = []
    fac_indexes.each do |index|
      get_tenants.each do |tenant|
        result_facility_indexes << index.gsub('tenant', tenant)
      end
    end
    result_facility_indexes
  end

  def get_provider_single_doc_indexes
    pr_indexes = %w[practitioner_role_tenant_rw]
    result_provider_indexes = []
    pr_indexes.each do |index|
      get_tenants.each do |tenant|
        result_provider_indexes << index.gsub('tenant', tenant)
      end
    end
    result_provider_indexes
  end

  def get_facility_single_doc_indexes
    fac_indexes = %w[organization_affiliation_tenant_rw]
    result_facility_indexes = []
    fac_indexes.each do |index|
      get_tenants.each do |tenant|
        result_facility_indexes << index.gsub('tenant', tenant)
      end
    end
    result_facility_indexes
  end

  def get_entity_type(index_name)
    if get_provider_single_doc_indexes.include?(index_name)
      'provider_single_doc'
    elsif get_facility_single_doc_indexes.include?(index_name)
      'facility_single_doc'
    elsif get_provider_indexes.include?(index_name)
      'provider'
    elsif get_facility_indexes.include?(index_name)
      'facility'
    end
  end

  def form_elastic_query(params, entity_type)
    if %w[facility facility_single_doc].include?(entity_type)
      ElasticSearchHelper::Facility.form_all_facility_elastic_query(params, entity_type)
    else
      ElasticSearchHelper::Provider.form_all_provider_elastic_query(params, entity_type)
    end
  end

end

app/helpers/elastic_search_helper.rb
module ElasticSearchHelper

  class Facility
    def self.name(name)
      {
        "nested": {
          "path": "organizationAffiliation.facility",
          "query": {
            "bool": {
              "must": [
                {
                  "match": {
                    "organizationAffiliation.facility.name": {
                      "query": "#{name}",
                      "operator": "and"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    end

    def self.identifier(identifier)
      {
        "nested": {
          "path": "organizationAffiliation.facility.identifier",
          "query": {
            "bool": {
              "must": [
                {
                  "match": {
                    "organizationAffiliation.facility.identifier.value": {
                      "query": "#{identifier}",
                      "operator": "and"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    end

    def self.source_name(name)
      {
        "match": {
          "organizationAffiliation.meta.source": {
            "query": "#{name}",
            "operator": "and"
          }
        }
      }
    end

    def self.updated_date(updated_date)
      {
        "match": {
          "organizationAffiliation.meta.updated": {
            "query": "#{updated_date}",
            "operator": "and"
          }
        }
      }
    end

    def self.stable_id(stable_id)
      {
        "nested": {
          "path": "organizationAffiliation.facility",
          "query": {
            "bool": {
              "must": [
                {
                  "match": {
                    "organizationAffiliation.facility.stableId": {
                      "query": "#{stable_id}",
                      "operator": "and"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    end

    def self.loc_stable_id(loc_stable_id)
      {
        "nested": {
          "path": "organizationAffiliation.location",
          "query": {
            "bool": {
              "must": [
                {
                  "match": {
                    "organizationAffiliation.location.stableId": {
                      "query": "#{loc_stable_id}",
                      "operator": "and"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    end

    def self.address_text(text)
      {
        "nested": {
          "path": "organizationAffiliation.location",
          "query": {
            "nested": {
              "path": "organizationAffiliation.location.address",
              "query": {
                "match": {
                  "organizationAffiliation.location.address.text": {
                    "query": "#{text}",
                    "operator": "and"
                  }
                }
              }
            }
          }
        }
      }
    end

    def self.address_city(city)
      {
        "nested": {
          "path": "organizationAffiliation.location",
          "query": {
            "nested": {
              "path": "organizationAffiliation.location.address",
              "query": {
                "match": {
                  "organizationAffiliation.location.address.city": {
                    "query": "#{city}",
                    "operator": "and"
                  }
                }
              }
            }
          }
        }
      }
    end

    def self.address_state(state)
      {
        "nested": {
          "path": "organizationAffiliation.location",
          "query": {
            "nested": {
              "path": "organizationAffiliation.location.address",
              "query": {
                "match": {
                  "organizationAffiliation.location.address.state": {
                    "query": "#{state}",
                    "operator": "and"
                  }
                }
              }
            }
          }
        }
      }
    end

    def self.address_zip(zip)
      {
        "nested": {
          "path": "organizationAffiliation.location",
          "query": {
            "nested": {
              "path": "organizationAffiliation.location.address",
              "query": {
                "match": {
                  "organizationAffiliation.location.address.postalCode": {
                    "query": "#{zip}",
                    "operator": "and"
                  }
                }
              }
            }
          }
        }
      }
    end

  end

  class Provider

  end

end

app/views/elastic_search/choose_index.html.erb
<section class="vh-100 bg-light">

  <h2 class="fw-bold mb-1 text-center pt-3">Please Choose Index</h2>

  <div class="container p-4 row m-auto">
    <div class="col-md-6 text-center">
      <table class="table table-bordered">
        <thead>
        <tr>
          <th scope="col">Provider</th>
        </tr>
        </thead>
        <tbody>
        <% @provider_indexes.each do |index| %>
          <tr>
            <td><%= link_to index, elasticsearch_search_form_path(index_name: index), class: "text-dark", style: "text-decoration:none;" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-6 text-center">
      <table class="table table-bordered">
        <thead>
        <tr>
          <th scope="col">Facility</th>
        </tr>
        </thead>
        <tbody>
        <% @facility_indexes.each do |index| %>
          <tr>
            <td><%= link_to index, elasticsearch_search_form_path(index_name: index), class: "text-dark", style: "text-decoration:none;" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

</section>

app/views/elastic_search/login.html.erb
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2">Login Elastic Search</h2>
              <br>

              <%= form_tag({ controller: "elastic_search", action: "authenticate" }, method: "post", multipart: true) do %>

                <div class="form-outline form-white mb-4">
                  <%= text_field_tag :ip_address, nil, required: true, placeholder: 'Enter IP address', class: 'form-control' %>
                </div>

                <div class="form-outline form-white mb-4">
                  <%= text_field_tag :port, nil, required: true, placeholder: 'Enter port', class: 'form-control' %>
                </div>

                <% if @auth.present? %>
                  <div class="form-outline form-white mb-4">
                    <%= text_field_tag :username, 'elastic', required: true, placeholder: 'Enter username', class: 'form-control' %>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <%= password_field_tag :password, nil, required: true, placeholder: 'Enter password', class: 'form-control' %>
                  </div>
                <% end %>

                <%= text_field_tag :auth, @auth, required: true, hidden: true %>

                <%= submit_tag "Proceed", class: "btn btn-success" %>
              <% end %>

            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/elastic_search/search_form.html.erb
<section class="vh-100 bg-light">

  <% if session[:entity_type] == 'provider' %>
    <%= render 'elastic_search/search_form/provider_search_form' %>
  <% elsif session[:entity_type] == 'facility' %>
    <%= render 'elastic_search/search_form/facility_search_form' %>
  <% elsif session[:entity_type] == 'provider_single_doc' %>
    <%= render 'elastic_search/search_form/provider_single_doc_search_form' %>
  <% elsif session[:entity_type] == 'facility_single_doc' %>
    <%= render 'elastic_search/search_form/facility_single_doc_search_form' %>
  <% end %>

</section>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('myForm').addEventListener('reset', function() {
            const token = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
            fetch('/elasticsearch/clear_search_session', {
                method: 'DELETE',
                headers: {
                    'X-CSRF-Token': token
                }
            }).then(response => {
                if (response.ok) {
                    document.querySelector('#myForm input[name="inputName"]').value = '';
                    document.querySelector('#myForm input[name="inputNpi"]').value = '';
                    document.querySelector('#myForm input[name="inputSource"]').value = '';
                    document.querySelector('#myForm input[name="inputUpdatedDate"]').value = '';
                    document.querySelector('#myForm input[name="inputStableId"]').value = '';
                    document.querySelector('#myForm input[name="inputLocStableId"]').value = '';
                    document.querySelector('#myForm input[name="inputAddrText"]').value = '';
                    document.querySelector('#myForm input[name="inputAddrCity"]').value = '';
                    document.querySelector('#myForm input[name="inputAddrState"]').value = '';
                    document.querySelector('#myForm input[name="inputAddrZip"]').value = '';
                    document.querySelector('#myForm input[name="inputSize"]').value = '';
                }
            });
        });
    });
</script>

app/views/elastic_search/search_results.html.erb
<section class="vh-100 bg-light">

  <div class="container p-4">

    <h2 class="fw-bold mb-2 text-center pt-1">Search Results</h2>
    <p class="text-dark-50 mb-2 text-center"><%= session[:index_name] %></p>

    <p class="text-dark-50 mb-5 text-center">
      <button type="button" class="btn btn-primary p-1" data-bs-toggle="modal" data-bs-target="#searchquery">
        View Query
      </button>
    </p>

    <textarea id="search-query" style="display: none;"><%= JSON.pretty_generate(@search_query) %></textarea>

    <div class="container">
      <div class="row">
        <div class="col">
          <p class="text-dark-50 mb-1">Matched Count: <%= @response['hits']['hits'].count %></p>
        </div>
        <div class="col text-end">
          <p class="text-dark-50 mb-1">Size: <%= session[:inputSize] %></p>
        </div>
      </div>
    </div>

    <% if session[:entity_type] == 'provider' %>
      <%= render 'elastic_search/search_results/provider_search_results' %>
    <% elsif session[:entity_type] == 'facility' %>
      <%= render 'elastic_search/search_results/facility_search_results' %>
    <% elsif session[:entity_type] == 'provider_single_doc' %>
      <%= render 'elastic_search/search_results/provider_single_doc_search_results' %>
    <% elsif session[:entity_type] == 'facility_single_doc' %>
      <%= render 'elastic_search/search_results/facility_single_doc_search_results' %>
    <% end %>

  </div>

  <!-- Search Query Modal -->
  <div class="modal fade modal-lg" id="searchquery" data-bs-keyboard="false" tabindex="-1" aria-labelledby="searchqueryLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title text-dark" id="searchqueryLabel">Seach Query</h5>

          <div class="ms-3">
            <button class="btn p-1 text-center" onclick="copyContent()" id="copy-button">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard" viewBox="0 0 16 16">
                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"/>
                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"/>
              </svg>
              Copy Query
            </button>
          </div>

          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <pre id="json-output"></pre>
        </div>
      </div>
    </div>
  </div>

</section>


<script>
    function getJson() {
        try {
            return JSON.parse($('#search-query').val());
        } catch (ex) {
            alert('Wrong JSON Format: ' + ex);
        }
    }

    document.getElementById("json-output").textContent = JSON.stringify(getJson(), undefined, 2);

    let text = document.getElementById('json-output').innerHTML;
    const copyContent = async () => {
        try {
            await navigator.clipboard.writeText(text);
            var originalCopyBtn = document.getElementById('copy-button').innerHTML
            document.getElementById('copy-button').innerHTML = 'Copied';
            setTimeout(() => {
                document.getElementById('copy-button').innerHTML = originalCopyBtn;
            }, 1000);
        } catch (err) {
            console.error('Failed to copy: ', err);
        }
    }

</script>

app/views/elastic_search/view_cluster.html.erb
<section class="vh-100 bg-light">

  <% if session[:entity_type] == 'provider' %>
    <%= render 'elastic_search/view_cluster/provider_view_cluster' %>
  <% elsif session[:entity_type] == 'facility' %>
    <%= render 'elastic_search/view_cluster/facility_view_cluster' %>
  <% elsif session[:entity_type] == 'provider_single_doc' %>
    <%= render 'elastic_search/view_cluster/provider_single_doc_view_cluster' %>
  <% elsif session[:entity_type] == 'facility_single_doc' %>
    <%= render 'elastic_search/view_cluster/facility_single_doc_view_cluster' %>
  <% end %>

</section>

<script>
    function getJsonSingleDoc() {
        try {
            return JSON.parse($('#single-doc-result').val());
        } catch (ex) {
            // alert('Wrong JSON Format: in view_cluster ' + ex);
        }
    }

    document.getElementById("json-single-doc-output").textContent = JSON.stringify(getJsonSingleDoc(), undefined, 2);

    let text = document.getElementById('json-single-doc-output').innerHTML;
    const copyContent1 = async () => {
        try {
            await navigator.clipboard.writeText(text);
            var originalCopyBtn = document.getElementById('copy-button-1').innerHTML
            document.getElementById('copy-button-1').innerHTML = 'Copied';
            setTimeout(() => {
                document.getElementById('copy-button-1').innerHTML = originalCopyBtn;
            }, 1000);
        } catch (err) {
            console.error('Failed to copy: ', err);
        }
    }
</script>