config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/new_trigger_message'
  get 'home/new_excel_gen'
  get 'home/new_source_trigger'
  post 'home/file_process_trigger'
  post 'home/process_excel'
  post 'home/process_sources_trigger'

  get 'elasticsearch/login', to: 'elastic_search#login'
  post 'elasticsearch/authenticate', to: 'elastic_search#authenticate'
  delete 'elasticsearch/logout', to: 'elastic_search#logout'

  get 'elasticsearch/choose_index', to: 'elastic_search#choose_index'

  get 'elasticsearch/search_form', to: 'elastic_search#search_form'
  delete 'elasticsearch/clear_search_session', to: 'elastic_search#clear_search_session'
  get 'elasticsearch/search_results', to: 'elastic_search#search_results'
  get 'elasticsearch/view_cluster', to: 'elastic_search#view_cluster'

  get 'saga_json/login', to: 'saga_json#login'
  post 'saga_json/authenticate', to: 'saga_json#authenticate'
  delete 'saga_json/logout', to: 'saga_json#logout'

  get 'saga_json/search_form', to: 'saga_json#search_form'
  delete 'saga_json/clear_search_session', to: 'saga_json#clear_search_session'
  get 'saga_json/search_results', to: 'saga_json#search_results'

  post 'saga_json/refresh_saga_data', to: 'saga_json#refresh_saga_data'
  post 'saga_json/download_saga_report', to: 'saga_json#download_saga_report'

  get 'result_hash/get_input', to: 'result_hash#get_input'
  post 'result_hash/process_input', to: 'result_hash#process_input'
  get 'result_hash/index', to: 'result_hash#index'
  delete 'result_hash/clear_result_hash', to: 'result_hash#clear_result_hash'
  delete 'result_hash/clear_specific_result_hash', to: 'result_hash#clear_specific_result_hash'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Clarity</a>
  </div>

  <% if session[:elastic_ip].present? %>
    <ul class="navbar-nav mb-2 mb-lg-0">
      <li class="nav-item ">
        <h6 class="text-white p-1"><%= session[:elastic_ip] %></h6>
      </li>
      <li class="nav-item ">
        <%= button_to 'Logout', elasticsearch_logout_path, method: :delete %>
      </li>
    </ul>
  <% end %>

  <% if session[:saga_json_url].present? %>
    <ul class="navbar-nav mb-2 mb-lg-0">
      <li class="nav-item ">
        <h6 class="text-white p-1"><%= session[:saga_json_url].gsub('https://', '').gsub('-api.azurewebsites.net', '').gsub('-', '.') %></h6>
      </li>
      <li class="nav-item ">
        <%= button_to 'Logout', saga_json_logout_path, method: :delete %>
      </li>
    </ul>
  <% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clarity</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= favicon_link_tag 'satellite.ico' %>

  <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%#= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<section class="gradient-custom">
  <section class="vh-100 bg-light">
    <%= render 'layouts/nav' %>
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show w-25 p-2 mx-auto" role="alert">
        <%= notice %>
        <button type="button" class="btn-close mx-auto p-2" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show w-25 p-2 mx-auto" role="alert">
        <%= alert %>
        <button type="button" class="btn-close mx-auto p-2" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= yield %>
  </section>
</section>

<style>
    .gradient-custom {
        /* fallback for old browsers */
        background: #6a11cb;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));
        background-repeat: no-repeat;
        background-size: cover;
        min-width: 100%;
        min-height: 100vh;
    }

    .gradient-custom-blue {
        background-color: #5f59f7;
        background-repeat: no-repeat;
        background-size: cover;
        min-width: 100%;
        min-height: 100vh;
    }

    .navbar-nav {
        margin-left: auto;
    }

    .table-head th {
        position: sticky;
        top: 0;
        background-color: rgb(255, 255, 255);
        outline: 1px solid #e9ecef;
        border: none;
        outline-offset: -1px;
    }

    .scrollme {
        width: 1500px;
        max-width: 100%;
        overflow-x: auto;
        height: 600px;
    }

</style>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>